spring:
  application:
    name: greeting-service
  config:
    import:
      - optional:configserver://localhost:8888/
  cloud:
    config:
      profile: qa

server:
  port: 8081

greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
