spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/esteroliver/ConfigServer
                    default-label: main
                    search-paths:
                        - 'greeting-service'
server:
    port: 8888